### ISSUE TITLE
Hide Bus icon during school hours

### ISSUE THREAD

**Issue by selsayed25** [tjcsl/ion#1415]
## Feature description
- Hide the bus icon on the left navigation bar when school is in session ~~or outside the TJ network.~~

## Rationale for adding feature
- Similar to the poll icon, it is not really helpful during school day, or when you're not in school.

## Suggested implementation(s) (if applicable)
- Possibly make a time period, one between 7:45 AM to 9 AM for morning buses, and one between 3:45 PM and 4:30 PM for afternoon buses when students can access the app.
~~- Look into how printing is hidden when students aren't at TJ.~~

**Comment by Rushilwiz** [comment]
I'm going to have to disagree with this one. I understand the rationale, but I think that the Bus app is too vital at the end of the day that students who aren't connected to the network won't be able to see their buses.

It's alright to hide it purely based off of time, but I don't know if it's necessary.

**Comment by selsayed25** [comment]
Oh ok. I changed it a bit. I'll probably leave this issue open if people might see it as one, however thank you for your feedback! :)

**Comment by alanzhu0** [comment]
I agree with @Rushilwiz - the Bus app is quite important, and if people aren't on FCPS WiFi (which is a sizeable number) then they won't be able to access it. As for restricting based on time - see [context_processors.py, line 151](https://github.com/tjcsl/ion/blob/1d6fa91acb677f428ca49f09f13d1e01a97c6d7c/intranet/apps/context_processors.py) - the logic is already there. It's currently being bypassed because of an if statement that always causes `show_bus_nav` to be true if `bus_driver` is enabled.

**Comment by selsayed25** [comment]
Alright it seems that I'm wrong, and I don't think that this issue is important at the moment. Thank you all for the feedback!
