### ISSUE TITLE
Teachers should be able to view rosters of eighth-period activities they are not sponsoring

### ISSUE THREAD

**Issue by fwilson42** [tjcsl/ion#302]
The eighth period teacher interface currently only shows activities that the user is sponsoring. For teachers with sticky activities (i.e. physics and geosystems), it is useful to have the ability to view rosters for other activities (i.e. ones that they are not sponsoring).

Requested by Dr. Stickler

**Comment by jwoglom** [comment]
The official response from Mrs. Burch on this issue is that it is intended functionality. If a teacher wants to view the roster for an activity, they can type its name and search for it in the search box. From there they can see the days that the activity is scheduled and view the roster from there.

**Comment by pefoley2** [comment]
I would recommend improving the docs, so that people don't raise this concern again.

**Comment by fwilson42** [comment]
A note should probably be added on the attendance page about how to view non-sponsored activity rosters.

**Comment by jwoglom** [comment]
A comment was added on the take attendance page where a teacher sees their activity list.

**Comment by jwoglom** [comment]
This was requested by the Eighth period office due to teacher feedback...

**Comment by jwoglom** [comment]
...and added per c96d4b3
