### ISSUE TITLE
Eighth profile detail for teacher should have same table layout as student profile detail

### ISSUE THREAD

**Issue by tcyrus** [tjcsl/ion#309]
Requested by Dr. Gabor and Dr. Torbert

**Comment by jwoglom** [comment]
What do you mean, exactly?

**Comment by fwilson42** [comment]
Instead of simply showing a block list like the teacher interface currently shows, something like the eighth profile table, but with "take attendance" instead of "change" links, and showing activities that the user is sponsoring, instead of activities they are attending. It might look something like:

![this](https://i.imgur.com/6hNmsns.png)

Essentially, the "Eighth" button in the teacher interface is very inviting, and the eighth period interface displayed is very sparse. Yes, the primary workflow should be taking attendance using the links from the dashboard, but teachers will still click the "Eighth" button out of curiosity and because they think it will have more detailed/useful information/actions to take.

**Comment by jwoglom** [comment]
The sponsor widget exists for this reason, and eighth profile pages for teachers are rarely linked to or used in the application, but yes there should be similar layout there.

**Comment by jwoglom** [comment]
Done
