### ISSUE TITLE
Schedule API routes for specific days give null result for weekends

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#432]

**Comment by anonymoose2** [comment]
I feel like this behavior has been around so long that some changing it might break some applications. Thoughts, @theo-o?

**Comment by theo-o** [comment]
I personally feel that returning a date key with a null value on weekends is a bug.  If a valid date on the weekend is provided, the API should return the date as the value for the `date` key along with an empty dictionary for the `block_type` key.  Returning that the value of the `date` key is null does not make sense because it is still a valid date just one without any schedule associated.
We also do not make any promises regarding the backwards compatibility of the Ion API.
