### ISSUE TITLE
Investigate duplicate EighthSignup objects

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#629]
Ref: Sentry ION-CF

Investigate the cause for duplicate signups/
```
ValidationError: ['EighthSignup already exists for this user on this block.']
```

**Comment by anonymoose2** [comment]
Related to #457.

**Comment by anonymoose2** [comment]
A few notes:
* `EighthSignup.objects.create()` is only used in tests and the Iodine attendence importer.
* `EighthSignup()` is only used in the Eighth Admin "Copy Block" view, which is available from the "Import Activities" link on the "edit block" page.
* It looks like almost everything else (including `add_user()`) uses `EighthSignup.objects.create_signup()`, which does a duplicate check immediately before creating.
* However, when the user is switching from a single-block activity to a single-block activity, `add_user()` simply modifies the `EighthSignup` and `save()`s it. It's possible that this is a caching issue. If so, `invalidate_obj(existing_signup)` might fix this, or at least reduce the number of duplicate signups.

If it turns out not to be a caching issue (or at least, not *completely* a caching issue), I see a few options to help mitigate this:
1. Currently, `create_signup()` does a uniqueness check and then calls `create()`. Instead, we could make it construct an `EighthSignup()`, check for uniqueness, and *then* `save()`. `create()` just constructs a new object and then `save()`s it anyway, so this would essentially make the uniqueness check one step closer to the actual creation of the object.
2. We could make `EighthSignup.objects.create()` also perform a uniqueness check immediately _after_ saving. If the check fails, it could delete the object it just created and raise a `ValidationError`. This is probably the best solution we could get without going through the database.
3. We could add a `_BLOCK` (or similar) field to `EighthSignup` that gets set to `scheduled_activity.block` immediately before saving. This would allow us to add it to `EighthSignup.Meta.unique_together` (currently `(("user", "scheduled_activity"),)`), which would enforce per-user, per-block uniqueness on the database level.
This is the only way I can think of to be completely sure that duplicate signups will not be created. However, we would need to ensure that ALL code that creates `EighthSignup`s (including the two mentioned above) ensures that this field is set properly before saving.

Thoughts, @theo-o?

**Comment by theo-o** [comment]
Thanks for the analysis, @anonymoose2.

One of the biggest roadblocks to solving this very annoying issue is the lack of information of exactly what are the causes of duplicate `EighthSignup` objects (i.e. the methods, DB operations, and conditions that coalesce to create duplicate `EigithSignup`). Generally, when by the time we realize that there are duplicates, it is far too late to identify the root cause. One way to identify these issues could be to add code after the objects are created in `add_user()` to check for whether the signup is a duplicate and throwing a Sentry error when a duplicate is found.  To see the logic path, we could log debug statements throughout `add_user()` and send those breadcrumbs along with the Sentry error.

Together with the above,  I would like pursuing option 2 (along with your proposed cache fixes).

**Comment by theo-o** [comment]
It appears that we haven't had duplicate EighthSignups since the deployment of https://github.com/tjcsl/ion/commit/cc257a57a977bae9e9a77876d26ece9ed94819f7. I'm closing this issue. Feel free to reopen if this reappears.
